name: "Bazel"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BAZEL: bazelisk-linux-amd64
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        path: "~/.cache/bazel"  # See https://docs.bazel.build/versions/master/output_directories.html
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.4.0/$BAZEL"
        chmod +x $BAZEL
        sudo mv $BAZEL /usr/local/bin/bazel

    - name: Install Flex and GMP
      run: sudo apt-get update && sudo apt-get install flex libgmp-dev

    - name: Build p4c
      run: bazel build //... --verbose_failures

    - name: Build bazel/example
      run: cd ./bazel/example && bazel build //... --verbose_failures
